# Generated by Django 3.2.11 on 2022-01-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=150)),
                ('Types', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
