# Generated by Django 3.2.11 on 2022-04-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Completed', 'Completed')], default='Cash on Delivery', max_length=150),
        ),
    ]
