# Generated by Django 3.2.11 on 2022-04-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_payment_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
