# Generated by Django 3.2.11 on 2022-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220423_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('khalti', 'khalti')], default='Cash on Delivery', max_length=150),
        ),
    ]
