# Generated by Django 3.2.11 on 2022-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_payment_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_way',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Khalti', 'Khalti')], default='Cash on Delivery', max_length=150),
        ),
    ]
