# Generated by Django 4.2.3 on 2023-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_logintracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintracker',
            name='user',
        ),
        migrations.AddField(
            model_name='logintracker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
