# Generated by Django 4.2.3 on 2023-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_logintracker_user_logintracker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintracker',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
