# Generated by Django 4.2.3 on 2023-08-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_logintracker_modified_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintracker',
            old_name='email',
            new_name='username',
        ),
    ]
